#!/usr/bin/python

import os
files = os.listdir(os.getcwd())
print files

srts = [i for i in files if i[-3:] == "srt"] 


class Change(object):
    def __init__(self):
        self.lines = None
        self.result = None

    def openFile(self, fileName):
        self.fileName = fileName
        fh      = open(fileName, 'r')
        lines   = fh.readlines()
        self.lines = lines
        fh.close()

    def changeLine(self, eachLine):
        result = ""
        length = len(eachLine)
        i = 0
        while i < length:
            #print "i",i
            if eachLine[i] == ":":
                if eachLine[i:i+4] == ":000":
                    #print "if"
                    result += ",000"
                    i += 4
                else:
                    result += eachLine[i]
                    #print "else"
                    i += 1                
            else:
                result += eachLine[i]
                #print "else"
                i += 1
        return result

    def changeFile(self):
        result = []
        for k in self.lines:
            result.append(self.changeLine(k))
        self.result = result


    def write(self):
        fh = open("__"+self.fileName, "w")
        for i in self.result:
            fh.write(i)
        fh.close()
            


for i in srts:
    tempInstance = Change()
    tempInstance.openFile(i)
    tempInstance.changeFile()
    tempInstance.write()


