#!/usr/bin/python

import sys

print sys.argv[0]
print sys.argv[1]

a = open(sys.argv[1], 'r')

b = a.readlines()

print len(b)

fileWrite = open("result.html", 'w')

flag = 0
for i, j in enumerate(b):
    if j[0:4] == "<sty" or j[0:11] == '<div id=\"pf':
        flag = 1
    elif j[0:4] == "<scr" or j[0:4] == "</bo" or j[0:4] == "</ht":
        flag = 0
        
    if flag == 1:
        fileWrite.write(j)

fileWrite.close()
