#!/bin/bash

#read line by line
#change string 
#finally mv to rename
#a typical use of it is:
#    ls | grep vtt | bashRemame

dolphin "/media/kenshin/新加卷/1T_newD/0a_计算机相关书籍/flask四剑客/flask/OReily/"| okular "/media/kenshin/新加卷/1T_newD/0a_计算机相关书籍/flask四剑客/flask/OReily/bad.pdf"

