#!/bin/bash

name=$1;

withoutJava=${name/.java/}

fileName=$withoutJava.java;

echo $name
echo $fileName;

#umcomment folowwing to get simple compiling.
#javac $fileName;

#following is to with self defined class path.
javac $fileName -classpath /media/kenshin/linuxData/datasheet/gits/javalib/;


java $withoutJava > javatxt;
subl javatxt;
rm $withoutJava.class;


