#!/bin/bash

#remove all the files.
if [  -f ctxt ]; then
    rm ctxt;
fi

if [  -f ccompile ]; then
    rm ccompile;
fi

if [  -f a.out ]; then
    rm a.out;
fi

#get the fileName Without .c
name=$1;

withoutc=${name/.c/}






fileName=$withoutc.c;

echo compiling $withoutc;
gcc $fileName  2>ccompile;


if [  -f ccompile ]; then
    cat ccompile;
fi

if [  -f a.out ]; then
    ./a.out;
fi





